# -*- coding: utf-8 -*-
"""text_to_speech.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZPBxoViMpo_ArrLe_i8Hq_s7LZ544xYm
"""

!pip install gtts

!pip install playsound

import warnings
warnings.filterwarnings('ignore')

import gtts   #Import Google Text to Speech
from IPython.display import Audio   #Import Audio method from IPython's Display Class

text = input('enter something here: ')  #input text here

sound = gtts.gTTS(text,lang='en')  #Provide the string to convert to speech

sound_name = 'sound.mp3' # sound name is belong variable it's file name as a sound.mp3

sound.save(sound_name)    #save the string converted to speech as a sound_name file

Audio(sound_name)

